config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root to: 'pages#home'

  get "/thankyou", to: "pages#show", as: :page_show
  get 'review_all', to: 'surveys#review_all', as: :review_all


  resources :surveys, only: [:show] do
    resources :responses, only: [:new, :create]
    get 'review_one', to: 'surveys#review_one', as: :reviews
  end

  resources :teams, only: [ :index ] do
    resources :surveys, only: [:index, :create]
    get 'reviews_team', to: 'surveys#reviews_team', as: :reviews_team

  end

  resources :questions, only: [:show]
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
skip_before_action :authenticate_user!
 def new
   # response belongs to questio, question belongs to survey
   # if we want all question, find the suvey and fetch all the questions    @question = Question.find(params[:question_id])
   @survey = Survey.find(params[:survey_id])
   @questions = []

   @survey.questions.each do |question|
     @questions << question
   end
 end

 def create
   # receive a bunch of fields in params and create a bunch of responses
   # we want -> question id for each question, the rating and review for that question
   # out of this, create a response for each question
   # { response_1: { question_id: 15 ,rating: 5, review: "" }, response_2 }

   extract_responses.each do |response|
     new_response = Response.new(rating: response[:rating])
     new_response.user = current_user
     # directly set so that we avoid triggering an SQL query
     new_response.question = Question.find(response[:question_id])
     saved = new_response.save!
   end

   @survey = Survey.find(params[:survey_id])

   @review = Review.new(content: params[:review])
   @review.survey = @survey
   @review.save
   redirect_to page_show_path
 end

private

 def response_params
   params.require(:response).permit(:rating, :question, :user)
 end

 def extract_responses
   params.slice(:response_1, :response_2, :response_3, :response_4, :response_5).values
 end

end

app/views/responses/new.html.erb
<h1 class="orange-font text-center mid-font letter-spacing">Weekly survey</h1>
  <br><br>
 <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1">
  <div class="row">
    <br><br><br><br><br>
    <div class="picto-inline text-center">
      <h4 class="light-font"><%= image_tag asset_path("thumbs-up.svg"), class: "big-picto" %><br><br>Let's improve our workplace</h4>
      <h4 class="light-font"><%= image_tag asset_path("mask.svg"), class: "big-picto" %><br><br>Totally anonymous</h4>
      <h4 class="light-font"><%= image_tag asset_path("hourglass.svg"), class: "big-picto" %><br><br>30 seconds of your time</h4>
    </div>
  </div>
<br><br><br><br><br><br><br><br>
</div>
<div class="start-button-container"><button id="next" class="button button-orange">Start 🚀</button></div>

<div class="row">
 <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
   <%= form_tag survey_responses_path(@survey) do |f| %>
     <% @questions.each_with_index do |question, index| %>
       <% response_key = "response_#{index + 1}" %>
       <div class="question-container">
         <div class="question-content">
           <div class="slidecontainer">
             <%= label_tag  response_key, question.text, class: "orange-font big-font" %>
             <br><br>
             <%= range_field response_key, :rating, in: 0..5, class: "slider" %>
             <div class="question-scale light-grey-text light-font">
               <span>0</span>
               <span>1</span>
               <span>2</span>
               <span>3</span>
               <span>4</span>
               <span>5</span>
             </div>
             <!-- customise name of field for easier params -->
             <%= hidden_field_tag "#{response_key}[question_id]", question.id  %>
            <div class="question-next"><button id="next" class="button button-orange">Next</button></div>
           </div>
          </div>
        </div>
       <% end %>
      </div>
    </div>
     <!-- text field to ask for review -->

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
       <div class="question-container">
         <%= label_tag :review, "Something else in your mind?", class: "light-font light-grey-text big-font" %>
         <%= text_field_tag :review, "", class: 'form-control lg-input' %>
         <br><br>
        <div class="text-center"><%= submit_tag "Submit feedback", class: "button button-orange" %></div>
      </div>
    </div>
  </div>

        <% end %>