config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root to: 'pages#home'

  get "/thankyou", to: "pages#show", as: :page_show
  get 'review_all', to: 'surveys#review_all', as: :review_all


  resources :surveys, only: [:show] do
    resources :responses, only: [:new, :create]
    get 'review_one', to: 'surveys#review_one', as: :reviews
  end

  resources :teams, only: [ :index ] do
    resources :surveys, only: [:index, :create]
    get 'reviews_team', to: 'surveys#reviews_team', as: :reviews_team

  end

  resources :questions, only: [:show]
end

app/views/shared/cards/_collaboration_card.html.erb
<div class="card">
  <h4>Collaboration</h4>
  <p class="light-grey-text">Communication, support & transparency indicator </p>
  <div class="frame">
    <h4 class="light-font text-center"> The team is  </h4>
  <% if rating <= 1  %>
    <p class="text-center light-font light-grey-text">Enthusiastic</p>
    <p class="text-center light-font light-grey-text">Cooperative</p>
    <p class="text-center light-font light-grey-text">Neutral</p>
    <p class="text-center light-font light-grey-text">Difficult</p>
    <p class="text-center orange-font bold-font">DISRUPTIVE</p>
  <% elsif rating > 1 && rating <= 2 %>
    <p class="text-center light-font light-grey-text">Enthusiastic</p>
    <p class="text-center light-font light-grey-text">Cooperative</p>
    <p class="text-center light-font light-grey-text">Neutral</p>
    <p class="text-center orange-font bold-font">DIFFICULT</p>
    <p class="text-center light-font light-grey-text">Disruptive</p>
  <% elsif rating > 2 && rating <= 3 %>
    <p class="text-center light-font light-grey-text">Enthusiastic</p>
    <p class="text-center light-font light-grey-text">Cooperative</p>
    <p class="text-center orange-font bold-font">NEUTRAL</p>
    <p class="text-center light-font light-grey-text">Difficult</p>
    <p class="text-center light-font light-grey-text">Disruptive</p>
  <% elsif rating > 3 && rating <= 4 %>
    <p class="text-center light-font light-grey-text">Enthusiastic</p>
    <p class="text-center orange-font bold-font">COOPERATIVE</p>
    <p class="text-center light-font light-grey-text">Neutral</p>
    <p class="text-center light-font light-grey-text">Difficult</p>
    <p class="text-center light-font light-grey-text">Disruptive</p>
  <% elsif rating > 4 %>
    <p class="text-center orange-font bold-font">ENTHUSIASTIC</p>
    <p class="text-center light-font light-grey-text">Cooperative</p>
    <p class="text-center light-font light-grey-text">Neutral</p>
    <p class="text-center light-font light-grey-text">Difficult</p>
    <p class="text-center light-font light-grey-text">Disruptive</p>
  <% else rating = nil %>
   <p class="light-font light-grey-text"> No rating yet!</p>
  <% end %>
  </div>
</div>

app/views/shared/cards/_enterprise_culture_card.html.erb
  <div class="card">
    <h4>Enterprise culture</h4>
    <p class="light-grey-text">Engagement, trust & motivation indicator</p>
    <div class="frame">
      <h4 class="light-font text-center"> Culture score </h4>
      <p class="text-center giant-font bold-font orange-font"><%= rating.round(1) %><span class="orange-font bold-font regular-font">/5</span></p>
    </div>
  </div>

app/views/shared/cards/_global_rating.erb
<div class="card orange-card">
  <h4 class="margin-lefty">Global Happiness</h4>
  <p class="light-font baby-font margin-lefty">Evolution over time</p>
  <div class="frame-transparant">
      <%= content_tag :div, class: "ratings_tools", data: {ratings: Array(ratings), labels: Array(labels) } do %>
    <% end %>
    <canvas id="myChart" class="chart-dimensions"></canvas>
  </div>
  <% if params[:id] %>
    <%= link_to "Reviews", survey_reviews_path(@survey), class: "button button-white margin-topy" %>
  <% elsif params[:team_id] %>
    <%= link_to "Reviews", team_reviews_team_path(@team) , class: "button button-white margin-topy" %>
  <% else %>
    <%= link_to "Reviews", review_all_path, class: "button button-white margin-topy" %>
  <% end %>
</div>

app/views/shared/cards/_personal_growth_card.html.erb
<div class="card">
  <h4>Personal growth</h4>
  <p class="light-grey-text">Recognition, opportunity & involvement indicator</p>
  <div class="frame">
    <h4 class="light-font text-center"> Fullfilment barometer </h4>
    <br>
    <ul class="chart-skills" data-rating="<%= rating %>">
      <%= image_tag asset_path('needle.png'), class: "needle" %>
      <li><span>0</span></li>
      <li><span>1</span></li>
      <li><span>2</span></li>
      <li><span>3</span></li>
      <li><span>4</span></li>
      <li><span>5</span></li>
      <style></style>
    </ul>



  </div>
</div>

app/views/shared/cards/_tools_and_processes_card.html.erb
<div class="card">
  <h4 class="">Tools & Processes</h4>
  <p class="light-grey-text">Training, systems and methods indicator </p>
  <div class="frame">
  <h4 class="light-font text-center"> Effectiveness score </h4><br>
    <% if rating <= 1  %>
      <p class="picto-inline align-vertical-center margin-topy">
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
      </p>
    <% elsif rating > 1 && rating <= 2 %>
      <p class="picto-inline align-vertical-center margin-topy">
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
      </p>
    <% elsif rating > 2 && rating <= 3 %>
      <p class="picto-inline align-vertical-center margin-topy">
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
      </p>
    <% elsif rating > 3 && rating <= 4 %>
      <p class="picto-inline align-vertical-center margin-topy">
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("grey-star.svg"), class: "picto" %>
      </p>
    <% elsif rating > 4 %>
      <p class="picto-inline align-vertical-center margin-topy">
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
        <%= image_tag asset_path("orange-star.svg"), class: "picto" %>
      </p>
      <% else rating = nil %>
      <p class="light-font light-grey-text"> Waiting for data</p>
    <% end %>
    <br><br><br>
  </div>
</div>

app/views/shared/cards/_well_being_card.html.erb
<div class="card">
  <h4>Well being</h4>
  <p class="light-grey-text">Work-life balance, stress level and health indicator</p>
  <div class="frame">
    <h4 class="light-font text-center"> Weather of the team </h4>
    <% if rating <= 1  %>
      <p class="picto-inline"><%= image_tag asset_path("thunder.svg"), class: "big-picto" %></p>
    <% elsif rating > 1 && rating <= 2 %>
      <p class="picto-inline"><%= image_tag asset_path("rain.svg"), class: "big-picto" %></p>
    <% elsif rating > 2 && rating <= 3 %>
      <p class="picto-inline"><%= image_tag asset_path("cloudy.svg"), class: "big-picto" %></p>
    <% elsif rating > 3 && rating <= 4 %>
      <p class="picto-inline"><%= image_tag asset_path("sunnish.svg"), class: "big-picto" %></p>
    <% elsif rating > 4 %>
      <p class="picto-inline"><%= image_tag asset_path("sunny.svg"), class: "big-picto" %></p>
      <% else rating = nil %>
      <p class="light-font light-grey-text"> No rating yet!</p>
    <% end %>

    <p class="picto-inline">
      <span class="light-font light-grey-text small-font">Mediocre</span>
      <span class="light-font light-grey-text small-font">Poor</span>
      <span class="light-font light-grey-text small-font">Fair</span>
      <span class="light-font light-grey-text small-font">Good</span>
      <span class="light-font light-grey-text small-font">Excellent</span>

    </p>


    <p class="picto-inline">
    <%= image_tag asset_path("thunder.svg"), class: "picto" %>
    <%= image_tag asset_path("rain.svg"), class: "picto" %>
    <%= image_tag asset_path("cloudy.svg"), class: "picto" %>
    <%= image_tag asset_path("sunnish.svg"), class: "picto" %>
    <%= image_tag asset_path("sunny.svg"), class: "picto" %>
    </p>
  </div>
</div>