config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root to: 'pages#home'

  get "/thankyou", to: "pages#show", as: :page_show
  get 'review_all', to: 'surveys#review_all', as: :review_all


  resources :surveys, only: [:show] do
    resources :responses, only: [:new, :create]
    get 'review_one', to: 'surveys#review_one', as: :reviews
  end

  resources :teams, only: [ :index ] do
    resources :surveys, only: [:index, :create]
    get 'reviews_team', to: 'surveys#reviews_team', as: :reviews_team

  end

  resources :questions, only: [:show]
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :team
  has_many :questions
  has_many :responses, through: :questions
  has_many :reviews

  def average_tool_rating
    ratings = questions.find_by(category: Category.where(name: "Tools & Processes")).responses.pluck(:rating)
    return ratings.sum.to_f / ratings.size
  end

  def global_rating
    response_averages = [
      questions.find_by(category: Category.where(name: "Tools & Processes")).responses.average(:rating),
      questions.find_by(category: Category.where(name: "Personal growth")).responses.average(:rating),
      questions.find_by(category: Category.where(name: "Well being")).responses.average(:rating),
      questions.find_by(category: Category.where(name: "Collaboration")).responses.average(:rating),
      questions.find_by(category: Category.where(name: "Enterprise culture")).responses.average(:rating)
    ].select { |response| response }

    response_averages.sum.fdiv(response_averages.length)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    @team = Team.find(params[:team_id])

    @personal_growth_responses = []
    @team.questions.where(category: Category.first).each { |q| @personal_growth_responses << q.responses }
    @personal_growth = (@personal_growth_responses.flatten.pluck(:rating).sum.to_f / @personal_growth_responses.flatten.pluck(:rating).size.to_f).round(1)

    @well_being_responses = []
    @team.questions.where(category: Category.where(name: "Well being")).each { |q| @well_being_responses << q.responses }
    @well_being = (@well_being_responses.flatten.pluck(:rating).sum.to_f / @well_being_responses.flatten.pluck(:rating).size.to_f).round(1)

    @collaboration_responses = []
    @team.questions.where(category: Category.where(name: "Collaboration")).each { |q| @collaboration_responses << q.responses }
    @collaboration = (@collaboration_responses.flatten.pluck(:rating).sum.to_f / @collaboration_responses.flatten.pluck(:rating).size.to_f).round(1)

    @tools_responses = []
    @team.questions.where(category: Category.where(name: "Tools & Processes")).each { |q| @tools_responses << q.responses }
    @tools = (@tools_responses.flatten.pluck(:rating).sum.to_f / @tools_responses.flatten.pluck(:rating).size.to_f).round(1)

    # modify to only have one rating per survey, it's average
    @surveys = Survey.where(team: @team)
    @tools_labels = @surveys.pluck(:created_at).map { |date| date.strftime("%d/%m") }

    @tools_ratings = []
    @surveys.each { |survey| @tools_ratings << survey.average_tool_rating }

    @enterprise_culture_responses = []
    @team.questions.where(category: Category.where(name: "Enterprise culture")).each { |q| @enterprise_culture_responses << q.responses }
    @enterprise_culture = (@enterprise_culture_responses.flatten.pluck(:rating).sum.to_f / @enterprise_culture_responses.flatten.pluck(:rating).size.to_f).round(1)

    @global = ((@personal_growth + @well_being + @collaboration + @tools + @enterprise_culture)/5).round(1)

    @teams = Team.all


    #############

    @survey_dates = @surveys.pluck(:created_at).map { |date| date.strftime("%d/%m") }

    @overtime_global_ratings = []
    @surveys.each { |survey| @overtime_global_ratings << survey.global_rating }

    #############

    render 'surveys/global'
  end

  def show


    @team = Team.find(Survey.find(params[:id]).team_id)
    @teams = Team.all

    @survey = Survey.find(params[:id])
    @well_being_question = @survey.questions.where(category: Category.where(name: "Well being")).first
    @personal_growth_question = @survey.questions.where(category: Category.where(name: "Personal growth")).first
    @collaboration_question = @survey.questions.where(category: Category.where(name: "Collaboration")).first
    @tool_question = @survey.questions.where(category: Category.where(name: "Tools & Processes")).first
    @enterprise_culture_question = @survey.questions.where(category: Category.where(name: "Enterprise culture")).first

    @well_being_ratings = []
    @survey.questions.where(category: Category.where(name: "Well being")).first.responses.each { |r| @well_being_ratings << r.rating }
    @well_being = (@well_being_ratings.sum.to_f / @well_being_ratings.size.to_f).round(1)

    @personal_growth_ratings = []
    @survey.questions.where(category: Category.first).first.responses.each { |r| @personal_growth_ratings << r.rating }
    @personal_growth = (@personal_growth_ratings.sum.to_f / @personal_growth_ratings.size.to_f).round(1)


    @collaboration_ratings = []
    @survey.questions.where(category: Category.where(name: "Collaboration")).first.responses.each { |r| @collaboration_ratings << r.rating }
    @collaboration = (@collaboration_ratings.sum.to_f / @collaboration_ratings.size.to_f).round(1)

    @tools_ratings = []
    @survey.questions.where(category: Category.where(name: "Tools & Processes")).first.responses.each { |r| @tools_ratings << r.rating }
    @tools = (@tools_ratings.sum.to_f / @tools_ratings.size.to_f).round(1)

    @tools_labels = @survey.created_at.strftime("%m/%d/%Y")


    @enterprise_culture_ratings = []
    @survey.questions.where(category: Category.where(name: "Enterprise culture")).first.responses.each { |r| @enterprise_culture_ratings << r.rating }
    @enterprise_culture = (@enterprise_culture_ratings.sum.to_f / @enterprise_culture_ratings.size.to_f).round(1)

    @global = ((@personal_growth + @well_being + @collaboration + @tools + @enterprise_culture)/5).round(1)

    @users = []
    @responses = []

    Survey.find(params[:id]).team.users.each{|user| @users << user}
    Survey.find(params[:id]).questions.each {|question| question.responses.each{|response| @responses << response}}

    @responses_number = @responses.size / 5
    @users_number = @users.size
    @pourcentage = ((@responses_number.to_f / @users_number.to_f) * 100).round(0)

    @questions = @survey.questions.pluck(:text)

  end

# Pour le bouton, passer un argument team
  def create

    @team = Team.find(params[:team_id])

    @personal_growth_question_text = ["I have the opportunity to grow within the organization"]
    @well_being_question_text = ["I have the flexibility to take time off when I need to"]
    @collaboration_question_text = ["I can count on my colleagues when I need help"]
    @tools_question_text = ["I  have access to the resources needed to do my work properly"]
    @enterprise_culture_question_text = ["I consider myself an ambassador for my organization"]

    @survey = Survey.create!(team: Team.find(params[:team_id]))
    Question.create!(category: Category.first, text: @personal_growth_question_text.sample, survey: @survey )
    Question.create!(category: Category.find_by(name: "Well being"), text: @well_being_question_text.sample, survey: @survey )
    Question.create!(category: Category.find_by(name: "Collaboration"), text: @collaboration_question_text.sample, survey: @survey )
    Question.create!(category: Category.find_by(name: "Tools & Processes"), text: @tools_question_text.sample, survey: @survey )
    Question.create!(category: Category.find_by(name: "Enterprise culture"), text: @enterprise_culture_question_text.sample, survey: @survey )

    Team.find(params[:team_id]).users.each do |user|
      UserMailer.survey(user, @survey).deliver_later
    end
   end

   def review_one
     @reviews = Survey.find(params[:survey_id]).reviews

   end

   def reviews_team

    @surveys = []
    Team.find(params[:team_id]).surveys.each {|survey| @surveys << survey }
    @reviews = []
    @surveys.each {|survey| survey.reviews.each {|instance| @reviews << instance}}

    render 'surveys/review_one'
   end

   def review_all
    @surveys = []
    Survey.all.each {|survey| @surveys << survey }
    @reviews = []
    @surveys.each {|survey| survey.reviews.each {|instance| @reviews << instance}}

    render 'surveys/review_one'
   end

end


# categories.each do |category_name|
#   # create! categories
#   category = Category.create!(name: category_name)
#   # filling the surveys with category and questions
#   Survey.all.each do |survey|
#     question = Question.create!(category: category, text: "Are you happy?", survey: survey )
#     # giving 2 responses to the questions
#     Response.create!(rating: 5, question: question, user: survey.team.users.all.sample)
#     Response.create!(rating: 4, question: question, user: survey.team.users.all.sample)
#   end
# end

app/views/surveys/_collaboration_card.html.erb
<div class="card">
  <h4>Collaboration</h4>
  <p class="light-grey-text">communication, support & transparency indicator </p>
  <div class="frame">
    <h4 class="light-font text-center"> My team's state is </h4>
  <% if @collaboration <= 1  %>
    <p class="text-center light-font light-grey-text">Enthusiastic</p>
    <p class="text-center light-font light-grey-text">Cooperative</p>
    <p class="text-center light-font light-grey-text">Neutral</p>
    <p class="text-center light-font light-grey-text">Difficult</p>
    <p class="text-center orange-font bold-font">DISRUPTIVE</p>
  <% elsif @collaboration > 1 && @collaboration <= 2 %>
    <p class="text-center light-font light-grey-text">Enthusiastic</p>
    <p class="text-center light-font light-grey-text">Cooperative</p>
    <p class="text-center light-font light-grey-text">Neutral</p>
    <p class="text-center orange-font bold-font">DIFFICULT</p>
    <p class="text-center light-font light-grey-text">Disruptive</p>
  <% elsif @collaboration > 2 && @collaboration <= 3 %>
    <p class="text-center light-font light-grey-text">Enthusiastic</p>
    <p class="text-center light-font light-grey-text">Cooperative</p>
    <p class="text-center orange-font bold-font">NEUTRAL</p>
    <p class="text-center light-font light-grey-text">Difficult</p>
    <p class="text-center light-font light-grey-text">Disruptive</p>
  <% elsif @collaboration > 3 && @collaboration <= 4 %>
    <p class="text-center light-font light-grey-text">Enthusiastic</p>
    <p class="text-center orange-font bold-font">COOPERATIVE</p>
    <p class="text-center light-font light-grey-text">Neutral</p>
    <p class="text-center light-font light-grey-text">Difficult</p>
    <p class="text-center light-font light-grey-text">Disruptive</p>
  <% elsif @collaboration > 4 %>
    <p class="text-center orange-font bold-font">ENTHUSIASTIC</p>
    <p class="text-center light-font light-grey-text">Cooperative</p>
    <p class="text-center light-font light-grey-text">Neutral</p>
    <p class="text-center light-font light-grey-text">Difficult</p>
    <p class="text-center light-font light-grey-text">Disruptive</p>
  <% else @collaboration = nil %>
   <p class="light-font light-grey-text"> No rating yet!</p>
  <% end %>
  </div>
</div>

app/views/surveys/_enterprise_culture_card.html.erb
  <div class="card">
    <h4>Enterprise culture</h4>
    <p class="light-grey-text">engagement, trust & motivation indicator</p>
    <div class="frame">
      <h4 class="light-font text-center"> Team's rating </h4>
      <p class="text-center giant-font bold-font orange-font"><%= @enterprise_culture %><span class="orange-font bold-font regular-font">/5</span></p>
    </div>
  </div>

app/views/surveys/_personal_growth_card.html.erb
<div class="card">
  <h4>Personal growth</h4>
  <p class="light-grey-text">recognition, opportunity & involvement indicator</p>
  <div class="frame">
    <h4 class="light-font text-center"> Fullfilment gauge </h4>
    <p><%= @personal_growth %></p>

    <ul class="chart-skills">
      <li><span>1</span></li>
      <li><span>2</span></li>
      <li><span>3</span></li>
      <li><span>4</span></li>
      <li><span>5</span></li>
    </ul>

  </div>
</div>

app/views/surveys/_tool_card.html.erb
<div class="card">
  <h4>Tools & Processes</h4>
  <p class="light-grey-text">My team has access to everything they need</p>
  <div class="frame">
    <h4 class="light-font text-center"> Team's effectiveness </h4>
    <p><%= @tools %></p>
  </div>
</div>

app/views/surveys/create.js.erb
document.getElementById("flashes").innerHTML = "<%= j(render('shared/mail_sent_flash')) %>";

setTimeout(function() {
  $('.alert').slideUp()
}, 5000)

app/views/surveys/global.html.erb
<!--Main dashboard-->
<div class="flex-container">
  <div class="left">
    <div class="left-content">

      <% if ( current_user.role === "super_user" && (params[:id] != nil || params[:team_id] != nil) ) %>

        <div class="left-content-item">
          <%= image_tag(asset_path('teams'), class: "padding-right icon-size", id: "dash") %>

          <p>
          <%= link_to "All surveys results", teams_path, class: "orange-font"%>
          </p>
        </div>

        <div class="left-content-item">
          <%= image_tag(asset_path('dash-default'), class: "padding-right icon-size", id: "dash") %>

          <p>
          <%= link_to "All #{@team.name}'s results", team_surveys_path(@team), class: "orange-font"%>
          </p>
        </div>
        <div class="left-content-item">
          <%= image_tag asset_path("history-default"), class: "padding-right icon-size", id: "history" %>
          <p>Specific survey results</p>

        </div>
          <div class="margin-left">
          <% @team.surveys.each do |survey| %>
            <p><%= link_to "Survey of #{survey.created_at.strftime("%d/%m/%Y")}", survey_path(survey), class: "orange-font" %></p>
          <% end %>
          </div>

        <% elsif current_user.role === "super_user" %>

          <div class="left-content-item">
          <%= image_tag(asset_path('dash-default'), class: "padding-right icon-size", id: "dash") %>

          <p>
          <%= link_to "All surveys results", teams_path, class: "orange-font"%>
          </p>
          </div>

        <% else %>
          <div class="left-content-item">
          <%= image_tag(asset_path('dash-default'), class: "padding-right icon-size", id: "dash") %>

          <p>
          <%= link_to "All #{@team.name}'s results", team_surveys_path(@team), class: "orange-font"%>
          </p>
        </div>
        <div class="left-content-item">
          <%= image_tag asset_path("history-default"), class: "padding-right icon-size", id: "history" %>
          <p>Specific survey results</p>

        </div>
          <div class="margin-left">
          <% @team.surveys.each do |survey| %>
            <p><%= link_to "Survey of #{survey.created_at.strftime("%d/%m/%Y")}", survey_path(survey), class: "orange-font" %></p>
          <% end %>
          </div>

        <% end %>

    </div>
  </div>

  <div class="center">
    <div class="container">
      <div class="row">
        <div class="col-md-8">

          <!-- render title -->
          <% if @team %>
            <h1 class="orange-font light-font margin-lefty"><%= @team.name %> pulse</h1>
            <% if @survey %>
              <p class="orange-font">Survey of <%= @survey.created_at.strftime("%d/%m/%Y") %></p>
            <% end %>
          <% else %>
            <h1 class="orange-font light-font margin-lefty">Company pulse</h1>
          <% end %>

        </div>
        <div class="col-md-4">
          <% if current_user.super_user? %>
          <div class="dropdown right">
            <button class="dropbtn">Select a team <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
            <div class="dropdown-content">
              <!-- render dropdown -->
              <% @teams.each do |team| %>
                <%= link_to "#{team.name }", team_surveys_path(team) %>
              <% end %>
            </div>
          </div>
          <% else %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= render "shared/cards/global_rating", ratings: @overtime_global_ratings, labels: @survey_dates  %>
        </div>

        <div class="col-md-4">
          <%= render "shared/cards/well_being_card", rating: @well_being %>
        </div>

        <div class="col-md-4">
          <%= render "shared/cards/personal_growth_card", rating: @personal_growth %>
        </div>

        <div class="col-md-4">
          <%= render "shared/cards/tools_and_processes_card", rating: @tools   %>
        </div>

        <div class="col-md-4">
          <%= render "shared/cards/collaboration_card", rating: @collaboration %>
        </div>


        <div class="col-md-4">
          <%= render "shared/cards/enterprise_culture_card", rating: @enterprise_culture %>
        </div>


      </div>
    </div>
  </div>
  <div class="right">

  </div>
</div>

<% if params[:team_id] %>
  <%= render 'shared/modal' %>
<% end %>


<!-- waiting for the average given by the controller-->

app/views/surveys/review_one.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <% if params[:team_id] %>
        <h1 class="orange-font light-font margin-lefty"><%= @reviews.first.survey.team.name %>'s reviews</h1>
      <% elsif params[:survey_id] %>

        <h1 class="orange-font light-font margin-lefty"><%= @reviews.first.survey.team.name %>'s reviews on <%= @reviews.first.survey.created_at.strftime("%d/%m/%Y")%></h1>

      <% else %>
        <h1 class="orange-font light-font margin-lefty">All reviews</h1>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if params[:team_id] %>
        <%= link_to "Back to #{Team.find(params[:team_id]).name}'s dashboard", team_surveys_path(Team.find(params[:team_id])), class: "button button-white"%>
      <% elsif params[:survey_id] %>
        <%= link_to "Back to survey", survey_path(Survey.find(params[:survey_id])), class: "button button-orange"%>
      <% else %>
        <%= link_to "Back to global dashboard", teams_path, class: "button button-white" %>
      <% end %>
    </div>
  </div>

<% @reviews.each do |review| %>

 <div class="container">
  <div class="card card-long-slim ">
    <p>From <%= review.survey.team.name %>'s team on
      <%= review.created_at.strftime("%d/%m/%Y") %></p>
      <h4>"<%=review.content %>"</h4>

  </div>
</div>
<% end %>


  <% if params[:team_id] %>
  <%= link_to "Back to #{Team.find(params[:team_id]).name}'s dashboard", team_surveys_path(Team.find(params[:team_id])), class: "button button-orange"%>
  <% end %>



</div>

app/views/surveys/show.html.erb
<!--Main dashboard-->
<div class="flex-container">
  <%= render "shared/sidebar" %>
  <div class="center">
    <div class="container">
      <div class="row">
        <div class="margin-lefty col-md-7">
          <% if @team %>
            <% if @survey %>
              <h2 class="light-font">Survey of <%= @survey.created_at.strftime("%A, %b %d  %Y") %></h2>
            <p>Completion (<%=@responses_number %>/<%=@users_number%> team members)</p>
            <div class="progress small-bar">
              <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="50"aria-valuemin="0"  aria-valuemax="100" style="width:<%= @pourcentage %>%"><%= @pourcentage %>%
              </div>
            </div>
            <% end %>
          <% else %>
            <h1 class="orange-font light-font">Company pulse</h1>
          <% end %>
        </div>
        <div class="col-md-3 margin-topy margin-lefty">
        <%= link_to "See your reviews", survey_reviews_path(@survey), class: "button button-orange" %>
        </div>
        <div class="col-md-4">
          <div class="dropdown right">

            <% if current_user.super_user? %>
            <button class="dropbtn">Select your team <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
            <% end%>

            <div class="dropdown-content">
              <!-- render dropdown -->
              <% @teams.each do |team| %>
                <%= link_to "#{team.name }", team_surveys_path(team) %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="row card-long-slim blank-card ">
        <div class="col-md-2 margin-center light-font light-grey-text">Categories</div>
          <div class="col-md-1 margin-center">
          <p class="light-font light-grey-text">Ratings</p>
        </div>
        <div class="col-md-6 margin-center">
          <p class="light-grey-text light-font">Survey's questions</p>
        </div>
      </div>

      <!-- CARDS / CATEGORIES  -->
      <div class="row card card-long-slim">
        <div class="col-md-2 margin-center">Well being</div>
          <div class="col-md-1 margin-center">
          <p class="light-font light-grey-text orange-font bold-font"><%= (@well_being).round(1) %>/5</p>
        </div>
        <div class="col-md-6 margin-center">
          <p class="light-grey-text">"<%= @questions.first %>"</p>
        </div>
      <div class="col-md-3 margin-center"><%= link_to 'Recommandations', question_path(@well_being_question), class: "button-small button-orange no-margin" %></div>
      </div>


      <div class="row card card-long-slim">
        <div class="col-md-2 margin-center">Personal growth</div>
          <div class="col-md-1 margin-center">
            <p class="light-font light-grey-text orange-font bold-font"><%= (@personal_growth).round(1) %>/5</p>
        </div>
        <div class="col-md-6 margin-center">
          <p class="light-grey-text">"<%= @questions.second %>"</p>
        </div>
      <div class="col-md-3 margin-center"><%= link_to 'Recommandations', question_path(@personal_growth_question), class: "button-small button-orange no-margin" %></div>
      </div>

      <div class="row card card-long-slim">
        <div class="col-md-2 margin-center">Collaboration</div>
          <div class="col-md-1 margin-center">
           <p class="light-font light-grey-text orange-font bold-font"><%= (@collaboration).round(1) %>/5</p>
        </div>
        <div class="col-md-6 margin-center">
          <p class="light-grey-text">"<%= @questions.third %>"</p>
        </div>
      <div class="col-md-3 margin-center"><%= link_to 'Recommandations', question_path(@collaboration_question), class: "button-small button-orange no-margin" %></div>
      </div>

      <div class="row card card-long-slim">
        <div class="col-md-2 margin-center">Tools & Processes</div>
          <div class="col-md-1 margin-center">
            <p class="light-font light-grey-text orange-font bold-font"><%= (@tools).round(1) %>/5</p>
        </div>
        <div class="col-md-6 margin-center">
          <p class="light-grey-text">"<%= @questions.fourth %>"</p>
        </div>
      <div class="col-md-3 margin-center"><%= link_to 'Recommandations', question_path(@tool_question), class: "button-small button-orange no-margin" %></div>
      </div>

      <div class="row card card-long-slim">
        <div class="col-md-2 margin-center">Enterprise culture</div>
          <div class="col-md-1 margin-center">
            <p class="light-font light-grey-text orange-font bold-font"><%= (@enterprise_culture).round(1) %>/5</p>
        </div>
        <div class="col-md-6 margin-center">
          <p class="light-grey-text">"<%= @questions.fifth %>"</p>
        </div>
      <div class="col-md-3 margin-center"><%= link_to 'Recommandations', question_path(@enterprise_culture_question), class: "button-small button-orange no-margin" %></div>
      </div>
      <%= link_to "Back to Dashboard", team_surveys_path(@team), class: "button button-white" %>
      <br><br><br><br>
      </div>
    </div>
  </div>
  <div class="right">
  </div>
</div>
<% if params[:team_id] %>
  <%= render 'shared/modal' %>
<% end %>